openapi: 3.0.0
info:
  title: Infinity API
  description: Explains how to interact with API
  version: 1.0.0
servers:
  - url: "secret"
paths:
  /users:
    get:
      summary: Get a list of users
      description: Returns a list of users.
      responses:
        "200":
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userID:
                      type: string
                    email:
                      type: string
    post:
      summary: Create a new user or Update an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userID:
                  type: string
                email:
                  type: string
      responses:
        "201":
          description: User created successfully
        "400":
          description: Bad request
  /users/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Get user by ID
      responses:
        "200":
          description: A user object
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                  email:
                    type: string
        "404":
          description: User not found
    delete:
      summary: Delete user by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: User deleted successfully
        "404":
          description: User not found
